const ACTIVITY_TYPES = Object.freeze({
  // Auth
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
  USER_PASSWORD_RESET: 'USER_PASSWORD_RESET',
  VERIFY_EMAIL: 'VERIFY_EMAIL',

  // User
  USER_CREATED: 'USER_CREATED',
  USERS_CREATED_BULK: 'USERS_CREATED_BULK',
  USER_DELETED: 'USER_DELETED',
  USER_INFO_UPDATED: 'USER_INFO_UPDATED',
  USER_ADDRESS_UPDATED: 'USER_ADDRESS_UPDATED',
  USER_EMERGENCY_CONTACT_UPDATED: 'USER_EMERGENCY_CONTACT_UPDATED',
  USER_BANK_DETAIL_UPDATED: 'USER_BANK_DETAIL_UPDATED',
  USER_DEGREE_ADDED: 'USER_DEGREE_ADDED',
  USER_DEGREE_DELETED: 'USER_DEGREE_DELETED',
  USER_EXPERIENCE_ADDED: 'USER_EXPERIENCE_ADDED',
  USER_EXPERIENCE_DELETED: 'USER_EXPERIENCE_DELETED',
  USER_PAN_UPDATED: 'USER_PAN_UPDATED',
  USER_AADHAR_UPDATED: 'USER_AADHAR_UPDATED',
  USER_PROFILE_UPDATED: 'USER_PROFILE_UPDATED',
  USER_PASSWORD_UPDATED_BY_ID: 'USER_PASSWORD_UPDATED_BY_ADMIN',
  USER_PASSWORD_UPDATED_BY_SELF: 'USER_PASSWORD_UPDATED_BY_SELF',
  USER_INFO_DELETED: 'USER_INFO_DELETED',
  PROFILE_UPDATED_BY_ADMIN: 'PROFILE_UPDATED_BY_ADMIN',

  // App - Business
  BUSINESS_AREA_CREATED: 'BUSINESS_AREA_CREATED',
  BUSINESS_AREA_UPDATED: 'BUSINESS_AREA_UPDATED',
  BUSINESS_AREA_REMOVED: 'BUSINESS_AREA_REMOVED',

  // App - Department
  DEPARTMENT_CREATED: 'DEPARTMENT_CREATED',
  DEPARTMENT_UPDATED: 'DEPARTMENT_UPDATED',
  DEPARTMENT_REMOVED: 'DEPARTMENT_REMOVED',

  // App - GSTIN
  GSTIN_CREATED: 'GSTIN_CREATED',
  GSTIN_UPDATED: 'GSTIN_UPDATED',
  GSTIN_REMOVED: 'GSTIN_REMOVED',

  // App - Cost/Profit Center
  COST_PROFIT_CREATED: 'COST_PROFIT_CREATED',
  COST_PROFIT_UPDATED: 'COST_PROFIT_UPDATED',
  COST_PROFIT_DELETED: 'COST_PROFIT_DELETED',

  // App - Business Segment
  BUSINESS_SEGMENT_CREATED: 'BUSINESS_SEGMENT_CREATED',
  BUSINESS_SEGMENT_UPDATED: 'BUSINESS_SEGMENT_UPDATED',
  BUSINESS_SEGMENT_DELETED: 'BUSINESS_SEGMENT_DELETED',

  // App - Department Assignment
  DEPARTMENT_ASSIGNMENT_CREATED: 'DEPARTMENT_ASSIGNMENT_CREATED',
  DEPARTMENT_ASSIGNMENT_UPDATED: 'DEPARTMENT_ASSIGNMENT_UPDATED',
  DEPARTMENT_ASSIGNMENT_DELETED: 'DEPARTMENT_ASSIGNMENT_DELETED',

  // App - Plant
  PLANT_CREATED: 'PLANT_CREATED',
  PLANT_UPDATED: 'PLANT_UPDATED',
  PLANT_REMOVED: 'PLANT_REMOVED',

  // Material - General Ledger
  GENERAL_LEDGER_CREATED: 'GENERAL_LEDGER_CREATED',
  GENERAL_LEDGER_UPDATED: 'GENERAL_LEDGER_UPDATED',
  GENERAL_LEDGER_DELETED: 'GENERAL_LEDGER_DELETED',

  // HSN
  HSN_CREATED: 'HSN_CREATED',
  HSN_UPDATED: 'HSN_UPDATED',
  HSN_DELETED: 'HSN_DELETED',
  HSN_BULK_CREATED: 'HSN_BULK_CREATED',

  // Material
  MATERIAL_CREATED: 'MATERIAL_CREATED',
  MATERIAL_UPDATED: 'MATERIAL_UPDATED',
  MATERIAL_DELETED: 'MATERIAL_DELETED',

  // Purchase Order Booking
  PO_BOOKING_CREATED: 'PO_BOOKING_CREATED',
  PO_BOOKING_CANCELLED: 'PO_BOOKING_CANCELLED', // optional if needed
  PO_BOOKING_DELETED: 'PO_BOOKING_DELETED',

  // Purchase Order Events
  PURCHASE_ORDER_CREATED: 'PURCHASE_ORDER_CREATED',
  PURCHASE_ORDER_UPDATED: 'PURCHASE_ORDER_UPDATED',
  PURCHASE_ORDER_DELETED: 'PURCHASE_ORDER_DELETED',
  PURCHASE_ORDER_SUBMITTED: 'PURCHASE_ORDER_SUBMITTED',
  PURCHASE_ORDER_APPROVED: 'PURCHASE_ORDER_APPROVED',
  PURCHASE_ORDER_REJECTED: 'PURCHASE_ORDER_REJECTED',

  // Customer Events
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',         // createCustomer
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',         // updateCustomer
  CUSTOMER_DELETED: 'CUSTOMER_DELETED',         // deleteCustomer (soft delete)
  CUSTOMER_SUBMITTED: 'CUSTOMER_SUBMITTED',     // maker submits customer for checker
  CUSTOMER_APPROVED: 'CUSTOMER_APPROVED',       // checker approves
  CUSTOMER_REJECTED: 'CUSTOMER_REJECTED',       // checker rejects
  CUSTOMER_CHECKER_ASSIGNED: 'CUSTOMER_CHECKER_ASSIGNED', // assignChecker

  // Sales Order Events
  SALES_ORDER_CREATED: 'SALES_ORDER_CREATED',       // createSalesOrder
  SALES_ORDER_UPDATED: 'SALES_ORDER_UPDATED',       // updateSalesOrder
  SALES_ORDER_DELETED: 'SALES_ORDER_DELETED',       // deleteSalesOrder (soft delete)
  SALES_ORDER_APPROVED: 'SALES_ORDER_APPROVED',     // approveSalesOrder
  SALES_ORDER_REJECTED: 'SALES_ORDER_REJECTED',     // rejectSalesOrder

  // Sales Verification Config Events
  SALES_VERIFICATION_CONFIG_CREATED: 'SALES_VERIFICATION_CONFIG_CREATED',   // first time created (upsert insert)
  SALES_VERIFICATION_CONFIG_UPDATED: 'SALES_VERIFICATION_CONFIG_UPDATED',   // updateMakerCheckerConfig / updateWorkflowSettings / updateNotificationSettings
  SALES_VERIFICATION_CONFIG_DELETED: 'SALES_VERIFICATION_CONFIG_DELETED',   // if ever soft delete implemented in future

  SALES_MAKER_CHECKER_CONFIG_CREATED: 'SALES_MAKER_CHECKER_CONFIG_CREATED',
  SALES_MAKER_CHECKER_CONFIG_UPDATED: 'SALES_MAKER_CHECKER_CONFIG_UPDATED',

  SALES_WORKFLOW_SETTINGS_CREATED: 'SALES_WORKFLOW_SETTINGS_CREATED',
  SALES_WORKFLOW_SETTINGS_UPDATED: 'SALES_WORKFLOW_SETTINGS_UPDATED',

  SALES_NOTIFICATION_SETTINGS_CREATED: 'SALES_NOTIFICATION_SETTINGS_CREATED',
  SALES_NOTIFICATION_SETTINGS_UPDATED: 'SALES_NOTIFICATION_SETTINGS_UPDATED',

  // Purchase
  PUCRCHASE_CREATE_SUPPLIER: 'PUCRCHASE_CREATE_SUPPLIER',
  
  // Supplier Events
  SUPPLIER_CREATED: 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED: 'SUPPLIER_UPDATED',
  SUPPLIER_DELETED: 'SUPPLIER_DELETED',
  SUPPLIER_SUBMITTED: 'SUPPLIER_SUBMITTED',
  SUPPLIER_APPROVED: 'SUPPLIER_APPROVED',
  SUPPLIER_REJECTED: 'SUPPLIER_REJECTED',

  SUPPLIER_SUBMITTED: 'SUPPLIER_SUBMITTED',
  SUPPLIER_APPROVED: 'SUPPLIER_APPROVED',
  SUPPLIER_REJECTED: 'SUPPLIER_REJECTED',

  // Supplier Verification
  SUPPLIER_VERIFICATION_FIELD_VERIFIED: 'SUPPLIER_VERIFICATION_FIELD_VERIFIED',
  SUPPLIER_VERIFICATION_BATCH_COMPLETED: 'SUPPLIER_VERIFICATION_BATCH_COMPLETED',
  SUPPLIER_VERIFICATION_MANUAL_OVERRIDE: 'SUPPLIER_VERIFICATION_MANUAL_OVERRIDE',
  SUPPLIER_CHECKER_ASSIGNED: 'SUPPLIER_CHECKER_ASSIGNED',
  SUPPLIER_CHECKER_ACTION_COMPLETED: 'SUPPLIER_CHECKER_ACTION_COMPLETED',
  SUPPLIER_VERIFICATION_UPDATED: 'SUPPLIER_VERIFICATION_UPDATED',

  // Verification Config
  VERIFICATION_CONFIG_CREATED: 'VERIFICATION_CONFIG_CREATED',
  VERIFICATION_CONFIG_UPDATED: 'VERIFICATION_CONFIG_UPDATED',
  VERIFICATION_CONFIG_RESET: 'VERIFICATION_CONFIG_RESET',
  VERIFICATION_REQUIREMENTS_UPDATED: 'VERIFICATION_REQUIREMENTS_UPDATED',
  MAKER_CHECKER_CONFIG_UPDATED: 'MAKER_CHECKER_CONFIG_UPDATED',
  MAKER_CHECKER_CONFIG_CREATED: 'MAKER_CHECKER_CONFIG_CREATED',

  // Attendance
  HOLIDAY_ADDED: 'HOLIDAY_ADDED',

  // Core - Profile
  PROFILE_DELETED: 'PROFILE_DELETED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  ADDRESS_UPDATED: 'ADDRESS_UPDATED',
  EMERGENCY_CONTACT_UPDATED: 'EMERGENCY_CONTACT_UPDATED',
  BANK_DETAIL_UPDATED: 'BANK_DETAIL_UPDATED',
  DEGREE_ADDED: 'DEGREE_ADDED',
  DEGREE_DELETED: 'DEGREE_DELETED',
  EXPERIENCE_ADDED: 'EXPERIENCE_ADDED',
  EXPERIENCE_DELETED: 'EXPERIENCE_DELETED',
  PAN_UPDATED: 'PAN_UPDATED',
  AADHAR_UPDATED: 'AADHAR_UPDATED',
  ACCOUNT_ACTIVATED: "ACCOUNT_ACTIVATED",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",

  // Core - Setting
  COMPANY_DETAILS_UPDATED: 'COMPANY_DETAILS_UPDATED',
  USER_PASSWORD_UPDATED: 'USER_PASSWORD_UPDATED',

  // Generic CRUD
  GENERIC_DOCUMENT_CREATED: 'GENERIC_DOCUMENT_CREATED',
  GENERIC_DOCUMENT_UPDATED: 'GENERIC_DOCUMENT_UPDATED',
  GENERIC_DOCUMENT_DELETED: 'GENERIC_DOCUMENT_DELETED',

  // Assets
  ASSET_TYPE_CREATED: 'ASSET_TYPE_CREATED',
  ASSET_ADDED: 'ASSET_ADDED',
  ASSET_BULK_CREATED: 'ASSET_BULK_CREATED',

  ASSET_TYPE_UPDATED: 'ASSET_TYPE_UPDATED',
  ASSET_UPDATED: 'ASSET_UPDATED',
  ASSET_TRANSFER_APPROVED: 'ASSET_TRANSFER_APPROVED',
  ASSET_TRANSFER_REJECTED: 'ASSET_TRANSFER_REJECTED',

  ASSET_TRANSFER_REQUESTED: 'ASSET_TRANSFER_REQUESTED',

  ASSET_TYPE_DELETED: 'ASSET_TYPE_DELETED',
  ASSET_DELETED: 'ASSET_DELETED',

  // Wallet
  WALLET_BALANCE_FETCHED: 'WALLET_BALANCE_FETCHED',
  WALLET_TRANSACTIONS_FETCHED: 'WALLET_TRANSACTIONS_FETCHED',
  ALL_EMPLOYEE_BALANCES_FETCHED: 'ALL_EMPLOYEE_BALANCES_FETCHED',

  // Attendance Settings
  ATTENDANCE_SETTINGS_CREATED: 'ATTENDANCE_SETTINGS_CREATED',
  ATTENDANCE_SETTINGS_UPDATED: 'ATTENDANCE_SETTINGS_UPDATED',

  ATTENDANCE_WEEKLY_OFF_CREATED: 'ATTENDANCE_WEEKLY_OFF_CREATED',
  ATTENDANCE_WEEKLY_OFF_UPDATED: 'ATTENDANCE_WEEKLY_OFF_UPDATED',

  ATTENDANCE_WORKING_HOURS_CREATED: 'ATTENDANCE_WORKING_HOURS_CREATED',
  ATTENDANCE_WORKING_HOURS_UPDATED: 'ATTENDANCE_WORKING_HOURS_UPDATED',

  EMP_ATTENDANCE_SETTING_UPDATED: 'EMP_ATTENDANCE_SETTING_UPDATED',
  EMP_ATTENDANCE_SETTING_CREATED: 'EMP_ATTENDANCE_SETTING_CREATED',

  // Holidays
  HOLIDAY_ADDED: 'HOLIDAY_ADDED',
  HOLIDAY_DELETED: 'HOLIDAY_DELETED',

  // Attendance
  ATTENDANCE_MARKED_BY_ADMIN: 'ATTENDANCE_MARKED_BY_ADMIN',
  ATTENDANCE_MARKED_BY_EMP: 'ATTENDANCE_MARKED_BY_ADMIN',
  ATTENDANCE_REQUEST_STATUS_UPDATED: 'ATTENDANCE_REQUEST_STATUS_UPDATED',
  EMP_ATTENDANCE_UPDATED: 'EMP_ATTENDANCE_UPDATED',
  EMP_ATTENDANCE_MARKED: 'EMP_ATTENDANCE_MARKED',

  // Attendance Policy
  ATTENDANCE_POLICY_CREATED: 'ATTENDANCE_POLICY_CREATED',
  ATTENDANCE_POLICY_UPDATED: 'ATTENDANCE_POLICY_UPDATED',
  ATTENDANCE_POLICY_APPLIED_TO_ALL: 'ATTENDANCE_POLICY_APPLIED_TO_ALL',
  ATTENDANCE_POLICY_APPLIED_TO_SELECTED: 'ATTENDANCE_POLICY_APPLIED_TO_SELECTED',

  // Attendance Setting
  EMPLOYEE_ATTENDANCE_SETTING_CREATED: 'EMPLOYEE_ATTENDANCE_SETTING_CREATED',
  EMPLOYEE_ATTENDANCE_SETTING_UPDATED: 'EMPLOYEE_ATTENDANCE_SETTING_UPDATED',

  // Single Employee Marking
  ATTENDANCE_CREATED: 'ATTENDANCE_CREATED',
  ATTENDANCE_UPDATED: 'ATTENDANCE_UPDATED',

  // Bulk Upload
  BULK_ATTENDANCE_CREATED: 'BULK_ATTENDANCE_CREATED',


  // Expense Category
  EXPENSE_CATEGORY_CREATED: 'EXPENSE_CATEGORY_CREATED',
  EXPENSE_CATEGORY_UPDATED: 'EXPENSE_CATEGORY_UPDATED',
  EXPENSE_CATEGORY_DELETED: 'EXPENSE_CATEGORY_DELETED',

  // Expense Form
  EXPENSE_FORM_CREATED: 'EXPENSE_FORM_CREATED',
  EXPENSE_FORM_UPDATED: 'EXPENSE_FORM_UPDATED',

  // Allowance Events
  ALLOWANCE_CREATED: 'ALLOWANCE_CREATED',
  ALLOWANCE_UPDATED: 'ALLOWANCE_UPDATED',
  ALLOWANCE_DELETED: 'ALLOWANCE_DELETED',

  // Batch Events
  BATCH_CREATED: 'BATCH_CREATED',
  BATCH_UPDATED: 'BATCH_UPDATED',
  BATCH_DELETED: 'BATCH_DELETED',

  // Compensation Events
  COMPENSATION_CREATED: 'COMPENSATION_CREATED',
  COMPENSATION_UPDATED: 'COMPENSATION_UPDATED',
  COMPENSATION_DELETED: 'COMPENSATION_DELETED',

  // Deduction Events
  DEDUCTION_CREATED: 'DEDUCTION_CREATED',
  DEDUCTION_UPDATED: 'DEDUCTION_UPDATED',
  DEDUCTION_DELETED: 'DEDUCTION_DELETED',
  TOGGLE_ENABLED_DEDUCTION: 'TOGGLE_ENABLED_DEDUCTION',

  // DirectDeposit Events
  DIRECT_DEPOSIT_CREATED: 'DIRECT_DEPOSIT_CREATED',
  DIRECT_DEPOSIT_UPDATED: 'DIRECT_DEPOSIT_UPDATED',
  DIRECT_DEPOSIT_DELETED: 'DIRECT_DEPOSIT_DELETED',

  // Payslip Events
  PAYSLIP_CREATED: 'PAYSLIP_CREATED',
  PAYSLIP_UPDATED: 'PAYSLIP_UPDATED',
  PAYSLIP_DELETED: 'PAYSLIP_DELETED',

  // Payslip Settings Events
  PAYSLIP_SETTINGS_UPDATED: 'PAYSLIP_SETTINGS_UPDATED',
  PAYSLIP_SETTINGS_CREATED: 'PAYSLIP_SETTINGS_CREATED',

  // Rounding Setting Events
  ROUNDING_SETTING_UPDATED: 'ROUNDING_SETTING_UPDATED',
  ROUNDING_SETTING_CREATED: 'ROUNDING_SETTING_CREATED',

  // Salary Template Events
  SALARY_TEMPLATE_CREATED: 'SALARY_TEMPLATE_CREATED',
  SALARY_TEMPLATE_UPDATED: 'SALARY_TEMPLATE_UPDATED',
  SALARY_TEMPLATE_DELETED: 'SALARY_TEMPLATE_DELETED',

  // Salary Template Deduction Events
  SALARY_TEMPLATE_DEDUCTION_CREATED: 'SALARY_TEMPLATE_DEDUCTION_CREATED',
  SALARY_TEMPLATE_DEDUCTION_UPDATED: 'SALARY_TEMPLATE_DEDUCTION_UPDATED',
  SALARY_TEMPLATE_DEDUCTION_DELETED: 'SALARY_TEMPLATE_DEDUCTION_DELETED',

  // Settlement Events
  SETTLEMENT_CREATED: 'SETTLEMENT_CREATED',
  SETTLEMENT_UPDATED: 'SETTLEMENT_UPDATED',
  SETTLEMENT_DELETED: 'SETTLEMENT_DELETED',

  // Expense Claim
  EXPENSE_CLAIM_CREATED: 'EXPENSE_CLAIM_CREATED',
  EXPENSE_UPDATED: 'EXPENSE_UPDATED',

  // Form Events
  FORM_CREATED: 'FORM_CREATED',
  FORM_UPDATED: 'FORM_UPDATED',
  FORM_DELETED: 'FORM_DELETED',

  // Loan Events
  LOAN_CREATED: 'LOAN_CREATED',
  LOAN_UPDATED: 'LOAN_UPDATED',
  LOAN_DELETED: 'LOAN_DELETED',

  // Loan Repayment Events
  LOAN_REPAYMENT_CREATED: 'LOAN_REPAYMENT_CREATED',
  LOAN_REPAYMENT_UPDATED: 'LOAN_REPAYMENT_UPDATED',
  LOAN_REPAYMENT_DELETED: 'LOAN_REPAYMENT_DELETED',

  // PayPeriod Events
  PAY_PERIOD_CREATED: 'PAY_PERIOD_CREATED',
  PAY_PERIOD_UPDATED: 'PAY_PERIOD_UPDATED',
  PAY_PERIOD_DELETED: 'PAY_PERIOD_DELETED',

  // Tax Rule Events
  TAX_RULE_CREATED: 'TAX_RULE_CREATED',
  TAX_RULE_UPDATED: 'TAX_RULE_UPDATED',
  TAX_RULE_DELETED: 'TAX_RULE_DELETED',

  // TDS Config Events
  TDS_CONFIG_UPDATED: 'TDS_CONFIG_UPDATED',
  TDS_CONFIG_CREATED: 'TDS_CONFIG_CREATED',

  // User Events
  USER_CREATED_PAYROLL: 'USER_CREATED_PAYROLL',
  USER_UPDATED_PAYROLL: 'USER_UPDATED_PAYROLL',
  USER_DELETED_PAYROLL: 'USER_DELETED_PAYROLL',

  // User With Batch Events
  USER_WITH_BATCH_CREATED: 'USER_WITH_BATCH_CREATED',
  USER_WITH_BATCH_UPDATED: 'USER_WITH_BATCH_UPDATED',
  USER_WITH_BATCH_DELETED: 'USER_WITH_BATCH_DELETED',

  // YTD Import Events
  YTD_IMPORT_CREATED: 'YTD_IMPORT_CREATED',
  YTD_IMPORT_UPDATED: 'YTD_IMPORT_UPDATED',
  YTD_IMPORT_DELETED: 'YTD_IMPORT_DELETED',

  // Expense Comments
  EXPENSE_COMMENT_ADDED: 'EXPENSE_COMMENT_ADDED',
  EXPENSE_COMMENT_UPDATED: 'EXPENSE_COMMENT_UPDATED',
  EXPENSE_COMMENT_DELETED: 'EXPENSE_COMMENT_DELETED',

  // Leave Events
  LEAVE_POLICY_CREATED: 'LEAVE_POLICY_CREATED',
  LEAVE_POLICY_UPDATED: 'LEAVE_POLICY_UPDATED',
  LEAVE_POLICY_DELETED: 'LEAVE_POLICY_DELETED',
  LEAVE_BALANCE_UPDATED: 'LEAVE_BALANCE_UPDATED',
  LEAVE_BALANCE_CREATED: 'LEAVE_BALANCE_CREATED',
  LEAVE_POLICY_STATUS_UPDATED: 'LEAVE_POLICY_STATUS_UPDATED',
  LEAVE_REQUEST_CREATED: 'LEAVE_REQUEST_CREATED',
  LEAVE_REQUEST_STATUS_UPDATED: 'LEAVE_REQUEST_STATUS_UPDATED',
  LEAVE_BALANCE_RESET: 'LEAVE_BALANCE_RESET',
  LEAVE_REQUEST_CREATED_BY_EMPLOYEE: 'LEAVE_REQUEST_CREATED_BY_EMPLOYEE',
  LEAVE_BALANCE_UPDATED_BY_EMPLOYEE: 'LEAVE_BALANCE_UPDATED_BY_EMPLOYEE',
  LEAVE_REQUEST_DELETED_BY_EMPLOYEE: 'LEAVE_REQUEST_DELETED_BY_EMPLOYEE',
  LEAVE_REQUEST_STATUS_UPDATED_BY_EMPLOYEE: 'LEAVE_REQUEST_STATUS_UPDATED_BY_EMPLOYEE',

  // Task Manager
  ACTIVITY_CREATED: 'ACTIVITY_CREATED',
  MEMBER_CREATED: 'MEMBER_CREATED',
  MEMBER_DELETED: 'MEMBER_DELETED',
  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_DELETED: 'PROJECT_DELETED',
  PROJECT_UPDATED: 'PROJECT_UPDATED',
  TASK_CREATED: 'TASK_CREATED',
  TASK_REMOVED: 'TASK_REMOVED',
  TASK_UPDATED: 'TASK_UPDATED',
  WORKSPACE_CREATED: 'WORKSPACE_CREATED',
  WORKSPACE_DELETED: 'WORKSPACE_DELETED',
  WORKSPACE_UPDATED: 'WORKSPACE_UPDATED',
  SUBTASK_DELETED: 'SUBTASK_DELETED',
  SUBTASK_UPDATED: 'SUBTASK_UPDATED',
  PROJECT_ATTACHMENT_ADDED: 'PROJECT_ATTACHMENT_ADDED',
  PROJECT_ATTACHMENT_DELETED: 'PROJECT_ATTACHMENT_DELETED',
  TASK_ATTACHMENT_ADDED: 'TASK_ATTACHMENT_ADDED',
  TASK_ATTACHMENT_DELETED: 'TASK_ATTACHMENT_DELETED',
  SUBTASK_ATTACHMENT_ADDED: 'SUBTASK_ATTACHMENT_ADDED',
  SUBTASK_ATTACHMENT_DELETED: 'SUBTASK_ATTACHMENT_DELETED',
  SUBTASK_CREATED: 'SUBTASK_CREATED',

  // Policy
  POLICY_UPDATED: 'POLICY_UPDATED',
  POLICY_REMOVED: 'POLICY_REMOVED',
  POLICY_CREATED: 'POLICY_CREATED',

  // Permission
  PERMISSION_CREATED: 'PERMISSION_CREATED',
  PERMISSION_UPDATED: 'PERMISSION_UPDATED',
  PERMISSION_REMOVED: 'PERMISSION_REMOVED',
  PERMISSION_ADDED: 'FEATURE_ADDED_IN_PERMISSION',

  // Notice
  NOTICE_REMOVED: 'NOTICE_REMOVED',
  NOTICE_UPDATED: 'NOTICE_UPDATED',
  NOTICE_CREATED: 'NOTICE_CREATED',

  // Wallet
  WALLET_DEBITED: 'WALLET_DEBITED',
  WALLET_CREDITED: 'WALLET_CREDITED',
  WALLET_REFUNDED: 'WALLET_REFUNDED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  FILE_UPLOADED: 'FILE_UPLOADED',
  EXPENSE_CREATED: 'EXPENSE_CREATED',
  EXPENSE_UPDATED: 'EXPENSE_UPDATED',
  EXPENSE_DELETED: 'EXPENSE_DELETED',
  WALLET_ADDED: 'WALLET_ADDED',
  WALLET_STATUS_UPDATED: 'WALLET_STATUS_UPDATED',
  WALLET_REQUEST_CREATED: 'WALLET_REQUEST_CREATED',
  WALLET_REQUEST_APPROVED: 'WALLET_REQUEST_APPROVED',
  WALLET_REQUEST_REJECTED: 'WALLET_REQUEST_REJECTED',
  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
  NOTIFICATION_DELETED: 'NOTIFICATION_DELETED',
  NOTIFICATION_MARKED_AS_READ: 'NOTIFICATION_MARKED_AS_READ',
  NOTIFICATION_MARKED_ALL_AS_READ: 'NOTIFICATION_MARKED_ALL_AS_READ'
});

module.exports = ACTIVITY_TYPES;