const ACTIVITY_TYPES = Object.freeze({
  // Auth
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
  USER_PASSWORD_RESET: 'USER_PASSWORD_RESET',
  VERIFY_EMAIL: 'VERIFY_EMAIL',

  // User
  USER_CREATED: 'USER_CREATED',
  USERS_CREATED_BULK: 'USERS_CREATED_BULK',
  USER_DELETED: 'USER_DELETED',
  USER_INFO_UPDATED: 'USER_INFO_UPDATED',
  USER_ADDRESS_UPDATED: 'USER_ADDRESS_UPDATED',
  USER_EMERGENCY_CONTACT_UPDATED: 'USER_EMERGENCY_CONTACT_UPDATED',
  USER_BANK_DETAIL_UPDATED: 'USER_BANK_DETAIL_UPDATED',
  USER_DEGREE_ADDED: 'USER_DEGREE_ADDED',
  USER_DEGREE_DELETED: 'USER_DEGREE_DELETED',
  USER_EXPERIENCE_ADDED: 'USER_EXPERIENCE_ADDED',
  USER_EXPERIENCE_DELETED: 'USER_EXPERIENCE_DELETED',
  USER_PAN_UPDATED: 'USER_PAN_UPDATED',
  USER_AADHAR_UPDATED: 'USER_AADHAR_UPDATED',
  USER_PROFILE_UPDATED: 'USER_PROFILE_UPDATED',
  USER_PASSWORD_UPDATED_BY_ID: 'USER_PASSWORD_UPDATED_BY_ID',
  USER_PASSWORD_UPDATED_BY_SELF: 'USER_PASSWORD_UPDATED_BY_SELF',
  USER_INFO_DELETED: 'USER_INFO_DELETED',
  PROFILE_UPDATED_BY_ADMIN: 'PROFILE_UPDATED_BY_ADMIN',

  // App - Business
  BUSINESS_AREA_CREATED: 'BUSINESS_AREA_CREATED',
  BUSINESS_AREA_UPDATED: 'BUSINESS_AREA_UPDATED',
  BUSINESS_AREA_REMOVED: 'BUSINESS_AREA_REMOVED',

  // App - Department
  DEPARTMENT_CREATED: 'DEPARTMENT_CREATED',
  DEPARTMENT_UPDATED: 'DEPARTMENT_UPDATED',
  DEPARTMENT_REMOVED: 'DEPARTMENT_REMOVED',

  // App - GSTIN
  GSTIN_CREATED: 'GSTIN_CREATED',
  GSTIN_UPDATED: 'GSTIN_UPDATED',
  GSTIN_REMOVED: 'GSTIN_REMOVED',

  // App - Plant
  PLANT_CREATED: 'PLANT_CREATED',
  PLANT_UPDATED: 'PLANT_UPDATED',
  PLANT_REMOVED: 'PLANT_REMOVED',

  // Attendance
  HOLIDAY_ADDED: 'HOLIDAY_ADDED',

  // Core - Profile
  PROFILE_DELETED: 'PROFILE_DELETED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  ADDRESS_UPDATED: 'ADDRESS_UPDATED',
  EMERGENCY_CONTACT_UPDATED: 'EMERGENCY_CONTACT_UPDATED',
  BANK_DETAIL_UPDATED: 'BANK_DETAIL_UPDATED',
  DEGREE_ADDED: 'DEGREE_ADDED',
  DEGREE_DELETED: 'DEGREE_DELETED',
  EXPERIENCE_ADDED: 'EXPERIENCE_ADDED',
  EXPERIENCE_DELETED: 'EXPERIENCE_DELETED',
  PAN_UPDATED: 'PAN_UPDATED',
  AADHAR_UPDATED: 'AADHAR_UPDATED',

  // Core - Setting
  COMPANY_DETAILS_UPDATED: 'COMPANY_DETAILS_UPDATED',
  USER_PASSWORD_UPDATED: 'USER_PASSWORD_UPDATED',

  // Generic CRUD
  GENERIC_DOCUMENT_CREATED: 'GENERIC_DOCUMENT_CREATED',
  GENERIC_DOCUMENT_UPDATED: 'GENERIC_DOCUMENT_UPDATED',
  GENERIC_DOCUMENT_DELETED: 'GENERIC_DOCUMENT_DELETED',
});

module.exports = ACTIVITY_TYPES;
